version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

  flink:
    image: apache/flink:1.13.2-scala_2.11
    ports:
      - '8081:8081'
    depends_on:
      - kafka

  druid:
    image: apache/druid:0.21.1
    ports:
      - '8888:8888'
    depends_on:
      - flink

  grafana:
    image: grafana/grafana:8.1.2
    ports:
      - '3000:3000'
    depends_on:
      - druid

  app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - kafka
      - flink
      - druid
      - grafana